name = "Toposes"
uuid = "36a15fe6-6211-457f-8fdb-aa2e0d2f3052"
authors = [
	"Mohamed Barakat <mohamed.barakat@uni-siegen.de>",
	"Tom Kuhmichel <tom.kuhmichel@student.uni-siegen.de>",
	"Mario Román <mromang08@gmail.com>",
	"Fabian Zickgraf <f.zickgraf@dashdos.com>",
]
version = "0.1.7"

[deps]
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
CartesianCategories = "c5961c08-7b59-43f4-a15e-02b3e7c87ab8"

[compat]
julia = "1.11"
CAP = "0.4, 0.5"
CartesianCategories = "0.2, 0.3"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
FinSetsForCAP = "0a079e9b-4bc2-44fe-a89b-7607e4464786"

[targets]
test = ["Test", "Documenter", "FinSetsForCAP"]
